name: Build Overleaf

on:
  push:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      buildBaseImage:
        description: 'Build base image'
        required: false
        default: true
        type: boolean
      buildImage:
        description: 'Build image'
        required: false
        default: true
        type: boolean

jobs:
  build:
    strategy:
      matrix:
        include:
          - runs-on: ARM64
            architecture: arm64
            buildctl: "buildctl"
    runs-on: ${{ matrix.runs-on }}
    name: Build ${{ matrix.architecture }}
    steps:
      - name: Checkout Overleaf
        uses: actions/checkout@v4
        with:
          repository: "overleaf/overleaf"
          ref: "main"
          path: "${{ github.workspace}}/overleaf"
      - name: Login into Docker
        shell: bash
        run: |
          mkdir -p ~/.docker
          jq --arg hostname "${{ secrets.DOCKER_HOST }}" --arg username "${{ secrets.DOCKER_USERNAME }}" --arg password "${{ secrets.DOCKER_PASSWORD }}" \
            '. + {"auths": (.auths + {($hostname): { "auth": "\($username):\($password)" | @base64 } } ) }' -n > ~/.docker/config.json
      - name: Set up Buildkit
        if: ${{ matrix.architecture == 'amd64' }}
        shell: bash
        run: |
          curl -sL https://github.com/moby/buildkit/releases/download/v0.22.0/buildkit-v0.22.0.linux-amd64.tar.gz | sudo tar -xz  -C /usr && \
          sudo buildkitd &
      - name: Build base image
        working-directory: "${{ github.workspace }}/overleaf"
        if: ${{ inputs.buildBaseImage }}
        run: |
          mv server-ce/Dockerfile server-ce/actual-dockerfile && \
          mv server-ce/Dockerfile-base server-ce/Dockerfile && \
          sed -Ei 's/scheme-basic/scheme-full/' server-ce/Dockerfile && \
          ${{ matrix.buildctl }} build \
            --frontend dockerfile.v0 \
            --local context=. \
            --local dockerfile=server-ce \
            --opt platform="linux/${{ matrix.architecture }}" \
            --output type=image,\"name=${{ secrets.DOCKER_TAG }}:base-${{ matrix.architecture }}\",push=true,store=false && \
          mv server-ce/Dockerfile server-ce/Dockerfile-base && \
          mv server-ce/actual-dockerfile server-ce/Dockerfile
      - name: Build image
        working-directory: "${{ github.workspace }}/overleaf"
        if: ${{ inputs.buildImage }}
        run: |
          ${{ matrix.buildctl }} build \
            --frontend dockerfile.v0 \
            --local context=. \
            --local dockerfile=server-ce \
            --opt platform="linux/${{ matrix.architecture }}" \
            --opt build-arg:OVERLEAF_BASE_TAG="${{ secrets.DOCKER_TAG }}:base-${{ matrix.architecture }}" \
            --output type=image,\"name=${{ secrets.DOCKER_TAG }}:${{ matrix.architecture }}\",push=true,store=false
